language: python
os: linux
before_install:
- openssl aes-256-cbc -K $encrypted_21a1ba667d28_key -iv $encrypted_21a1ba667d28_iv
  -in admin_emailer_rsa.enc -out admin_emailer_rsa -d
- openssl aes-256-cbc -K $encrypted_040e7022ffcf_key -iv $encrypted_040e7022ffcf_iv
  -in abdul_emailer_rsa.enc -out abdul_emailer_rsa -d
- chmod 400 abdul_emailer_rsa
- scp  -i abdul_emailer_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null deploy.sh abdulrab@emailer-app-dev-1.abdulrabbani.com:/home/abdulrab/deploy.sh
script:
- echo "Hello World"
- ssh  -i abdul_emailer_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null abdulrab@emailer-app-dev-1.abdulrabbani.com	'/home/abdulrab/deploy.sh'
deploy:
  provider: lambda
  function_name: dev_emailer_trigger
  region: us-east-1
  role: arn:aws:iam::892324357486:role/iam_for_lambda
  runtime: python3.7
  handler_name: lambda_handler
  module_name: test
  zip: terraform/lambda/dev/emailer_trigger_code/test.py.zip
  on:
    branch: develop
