language: python
branches:
  only:
  - develop
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- docker build -t abdulrabbani00/emailer .
- docker run -d abdulrabbani00/emailer /bin/sh
- docker ps -a
