language: python
os: linux
#branches:
#  only:
#  - develop

before_install:
  - echo "Before "

script:
  - echo "Hello World"

deploy:
  provider: lambda
  function_name: "dev_emailer_trigger"
#    region: "us-east-1"
  role: "arn:aws:iam::892324357486:role/iam_for_lambda"
#    runtime: "python3.7"
#    handler_name: "test.lambda_handler"
  zip: "terraform/lambda/dev/emailer_trigger_code/test.py.zip"
  on:
    branch: develop
#services:
#- docker
#before_install:
#- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
#  -in id_rsa.enc -out id_rsa -d
#- docker build -t abdulrabbani00/emailer .
#- docker run -d abdulrabbani00/emailer /bin/sh
#- docker ps -a
